#support datasets:
#  nasbenchasr: timit.
bench_name: nasbenchasr
dataset: timit

data_path: data

#nasbenchasr:
#  cell
search_space_type: cell

# ----------------------------Training settings --------------------------------
search_type: search_steps

search_time: float('inf')
# target_steps: the number of sampled true archs.
target_steps: 300
rand_seed: -1
loops_if_rand: 20
workers: 2
steps_each_record: 20

# --------------------- LSTM-based agent (controller) ---------------------------
search_strategy: rl
# the number of Archs in one batch. # of episodes = batch size.
episodes: 20
# the number of batch per epoch. note that ensure: batchs_per_epoch * episodes = 100.
batchs_per_epoch: 10
# options: update_controller_algo = ppo and update_controller_iters = 5 (default) or
# update_controller_algo = pg and update_controller_iters = 1.
update_controller_algo: ppo
update_controller_iters: 5
clip_ratio: 0.2

controller_epochs: 20
controller_lr: 0.001
# 1e-3
controller_weight_decay: 0.001
# 1e-8
controller_eps: 0.00000001

# ----------------------- Predictor -----------------------------------------
# options: True or False
is_predictor: True

#xgboost for nasbenchasr
predictor_type: xgb

# options: None, all, fixed_k, adaptive.
predictor_mode: adaptive
fixedk: 2

is_ensemble: True
num_ensemble: 3

# the threshold of the adaptive method.
theta: 0.1

# ----------------------- log path -----------------------------------
log_path: ./outputs
