#support datasets:
#  nasbench201: cifar10, cifar100, and ImageNet-16.
bench_name: nasbench201
dataset: ImageNet16-120

data_path: data/NATS-tss-v1_0-3ffb9-simple

#nasbench201:
#  we use the natsbench instead of nasbench201.
#  natsbench support two types of search spaces: tss and sss.
#  we only use the tss.
search_space_type: tss

# ----------------------------Training settings --------------------------------
search_type: time_budget

# cifar10: 40000, cifar-100: 75000, ImageNet16-120: 200000.
search_time: 200000
target_steps: float('inf')
rand_seed: -1
loops_if_rand: 20
workers: 2
steps_each_record: 20

# --------------------- LSTM-based agent (controller) ---------------------------
search_strategy: rl
# the number of Archs in one batch. note that ensure: episodes * batchs_per_epoch = 100
episodes: 10
update_controller_algo: ppo
update_controller_iters: 5
clip_ratio: 0.2

controller_epochs: float('inf')
batchs_per_epoch: 10
controller_lr: 0.001
# 1e-3
controller_weight_decay: 0.001
# 1e-8
controller_eps: 0.00000001

# ----------------------- Predictor -----------------------------------------
# options: True or False
is_predictor: True

# seminas for nasbench201
predictor_type: seminas

# options: None, all, fixed_k, adaptive.
predictor_mode: fixed_k

# cifar10: 2, cifar-100: 5, ImageNet16-120: 2.
fixedk: 2

is_ensemble: True
num_ensemble: 3

# the threshold of the adaptive method.
theta: 0.1

# ----------------------- log path -----------------------------------
log_path: ./outputs
